<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Asymmetric\" />
    <Folder Include="Symmetric\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blake3" Version="2.2.1" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.0" />
    <PackageReference Include="SimpleBase" Version="5.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoKeyLab.Domain\CryptoKeyLab.Domain.csproj" />
  </ItemGroup>

</Project>
